"""initial schema

Revision ID: 2d4733f7ccba
Revises: 
Create Date: 2026-07-23 16:07:47.869108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d4733f7ccba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_status', sa.String(length=64), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_name', 'input_hash', name='uq_staging_name_hash')
    )
    op.create_index(op.f('ix_extraction_staging_ingredient_name'), 'extraction_staging', ['ingredient_name'], unique=False)
    op.create_index(op.f('ix_extraction_staging_input_hash'), 'extraction_staging', ['input_hash'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('synonyms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_table('ingredient_regulatory_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('normalized_status', sa.String(length=64), nullable=False),
    sa.Column('category_codes', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('citation_url', sa.Text(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('date_added', sa.String(length=7), nullable=True),
    sa.Column('source_staging_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['source_staging_id'], ['extraction_staging.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_regulatory_status_ingredient_id'), 'ingredient_regulatory_status', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_regulatory_status_ingredient_id'), table_name='ingredient_regulatory_status')
    op.drop_table('ingredient_regulatory_status')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_extraction_staging_input_hash'), table_name='extraction_staging')
    op.drop_index(op.f('ix_extraction_staging_ingredient_name'), table_name='extraction_staging')
    op.drop_table('extraction_staging')
    # ### end Alembic commands ###
