"""Postgres full-text search over canonical, current-state data.

Phase 1 search strategy (DATABASE_DESIGN.md Section 9): `tsvector` columns
generated by Postgres itself (see the `Computed(...)` mapping on each
model), backed by GIN indexes, queried via `plainto_tsquery`/`ts_rank`.
Sufficient until query volume or relevance needs outgrow it — a dedicated
search engine is deferred (ROADMAP.md's deferred-work table), not built
speculatively.

Every result is scoped to `RecordStatus.ACTIVE` current versions only —
retracted/superseded/withdrawn facts don't show up in search, matching
DATABASE_DESIGN.md Section 3's "application-level queries default to
filtering out retracted/non-current records."
"""

from collections.abc import Callable
from dataclasses import dataclass

import sqlalchemy as sa
from sqlalchemy.orm import Session

from database.models.alias import Alias
from database.models.enums import EntityType, RecordStatus, ReferenceType
from database.models.ingredient import Ingredient, IngredientVersion
from database.models.manufacturer import Manufacturer
from database.models.product import Product, ProductIngredient, ProductVersion
from database.models.recall import Recall
from database.models.reference import Reference
from database.models.source import Source
from database.models.warning import Warning

# DailyMed's real, public per-label page. Both openFDA and DailyMed ingestion
# attach a Reference(SPL_SET_ID) to every Product (see
# ingestion/openfda/persistence.py and ingestion/dailymed/persistence.py) --
# both sources' documents derive from the same FDA SPL corpus, so this link
# resolves regardless of which adapter actually ingested the record. This is
# what makes a citation independently verifiable rather than just a bulk-file
# identifier a user has no way to act on.
_DAILYMED_LABEL_URL = "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid={set_id}"


@dataclass(frozen=True)
class Provenance:
    source_system: str
    endpoint_or_document_type: str
    ingested_at: str


def _provenance(session: Session, source_id: int) -> Provenance:
    source = session.get(Source, source_id)
    assert source is not None  # source_id is a NOT NULL FK; the row always exists
    return Provenance(
        source_system=source.source_system,
        endpoint_or_document_type=source.endpoint_or_document_type,
        ingested_at=source.ingested_at.isoformat(),
    )


TsqueryBuilder = Callable[[str], sa.ColumnElement[str]]


def build_tsquery(query: str) -> sa.ColumnElement[str]:
    """AND across query words (the default, precise strategy): every
    non-stopword lexeme in `query` must appear in the document. Correct and
    high-precision for keyword-style queries (what the Search box sends).
    """
    return sa.func.plainto_tsquery("english", query)


def build_tsquery_or(query: str) -> sa.ColumnElement[str]:
    """OR across query words -- a deliberate fallback, not the default.

    Tried when `build_tsquery` (AND) finds nothing at all: a
    natural-language-ish question ("Tell me about the Serious Skincare
    product?") can otherwise return zero results the instant *any* single
    word ("tell", "product") doesn't appear verbatim in a record, even when
    the query's actual subject ("Serious Skincare") is a clean match on its
    own.

    Not used as the default everywhere: `ts_rank` isn't length/field-
    normalized across different tsvector sources (a short product name vs.
    a long warning paragraph), so under OR-matching a document matching one
    generic word in a long field can outrank a document matching several
    specific words in a short field -- verified empirically (a "Serious
    Skincare" product-name match at rank 0.034 was outranked by unrelated
    warning text matching only the generic word "product" at rank 0.064).
    Falling back to OR only when AND finds nothing keeps that precision
    problem from ever affecting a query that AND already answers well.
    """
    words = query.split()
    if not words:
        return sa.func.plainto_tsquery("english", query)
    combined: sa.ColumnElement[str] = sa.func.plainto_tsquery("english", words[0])
    for word in words[1:]:
        combined = combined.op("||")(sa.func.plainto_tsquery("english", word))
    return combined


def _dailymed_label_url(session: Session, product_id: str) -> str | None:
    set_id = session.execute(
        sa.select(Reference.reference_value).where(
            Reference.entity_type == EntityType.PRODUCT,
            Reference.entity_id == product_id,
            Reference.reference_type == ReferenceType.SPL_SET_ID,
        )
    ).scalar_one_or_none()
    return _DAILYMED_LABEL_URL.format(set_id=set_id) if set_id else None


@dataclass(frozen=True)
class IngredientHit:
    """No `external_url` here, deliberately: an ingredient isn't itself an
    SPL document -- it can appear across many products' labels, so there's
    no single correct page to link to (unlike Product/Warning/Recall, which
    each belong to exactly one product's label)."""

    id: str
    name: str
    rank: float
    product_ids: list[str]
    source: Provenance


def search_ingredients(
    session: Session,
    query: str,
    *,
    limit: int = 20,
    tsquery_builder: TsqueryBuilder = build_tsquery,
) -> list[IngredientHit]:
    """Matches on the canonical name *or* a known alias.

    Aliases matter here specifically: after entity resolution
    (ENTITY_RESOLUTION.md), "Vitamin C" is an alias of canonical "Ascorbic
    Acid" — searching the canonical name alone would never find it under
    the name a user is likely to actually search for.
    """
    tsquery = tsquery_builder(query)

    name_matches = session.execute(
        sa.select(
            Ingredient.id, sa.func.ts_rank(IngredientVersion.search_vector, tsquery).label("rank")
        )
        .join(IngredientVersion, IngredientVersion.id == Ingredient.current_version_id)
        .where(
            IngredientVersion.search_vector.op("@@")(tsquery),
            IngredientVersion.status == RecordStatus.ACTIVE,
        )
    ).all()

    alias_matches = session.execute(
        sa.select(
            Alias.entity_id, sa.func.ts_rank(Alias.search_vector, tsquery).label("rank")
        ).where(Alias.entity_type == EntityType.INGREDIENT, Alias.search_vector.op("@@")(tsquery))
    ).all()

    best_rank_by_id: dict[str, float] = {}
    for entity_id, rank in (*name_matches, *alias_matches):
        rank = float(rank)
        if entity_id not in best_rank_by_id or rank > best_rank_by_id[entity_id]:
            best_rank_by_id[entity_id] = rank

    top_ids = sorted(best_rank_by_id, key=lambda eid: best_rank_by_id[eid], reverse=True)[:limit]

    hits = []
    for ingredient_id in top_ids:
        ingredient = session.get(Ingredient, ingredient_id)
        if ingredient is None or ingredient.current_version is None:
            continue
        current = ingredient.current_version
        product_ids = list(
            session.execute(
                sa.select(Product.id)
                .join(
                    ProductIngredient,
                    ProductIngredient.product_version_id == Product.current_version_id,
                )
                .where(ProductIngredient.ingredient_id == ingredient_id)
            )
            .scalars()
            .all()
        )
        hits.append(
            IngredientHit(
                id=ingredient_id,
                name=current.name,
                rank=best_rank_by_id[ingredient_id],
                product_ids=product_ids,
                source=_provenance(session, current.source_id),
            )
        )
    return hits


@dataclass(frozen=True)
class IngredientRef:
    id: str
    name: str
    role: str


@dataclass(frozen=True)
class WarningRef:
    category: str
    text: str


@dataclass(frozen=True)
class RecallRef:
    id: int
    reason: str
    classification: str
    status: str


@dataclass(frozen=True)
class ManufacturerRef:
    id: str
    name: str


@dataclass(frozen=True)
class ProductHit:
    id: str
    name: str
    product_type: str | None
    dosage_form: str | None
    manufacturer: ManufacturerRef | None
    ingredients: list[IngredientRef]
    warnings: list[WarningRef]
    recalls: list[RecallRef]
    rank: float
    source: Provenance
    external_url: str | None


def _product_ingredients(session: Session, product_version_id: int) -> list[IngredientRef]:
    links = session.execute(
        sa.select(ProductIngredient).where(
            ProductIngredient.product_version_id == product_version_id
        )
    ).scalars()
    refs = []
    for link in links:
        ingredient = session.get(Ingredient, link.ingredient_id)
        if ingredient is not None and ingredient.current_version is not None:
            refs.append(
                IngredientRef(
                    id=ingredient.id, name=ingredient.current_version.name, role=link.role.value
                )
            )
    return refs


def _product_manufacturer(session: Session, manufacturer_id: str | None) -> ManufacturerRef | None:
    if manufacturer_id is None:
        return None
    manufacturer = session.get(Manufacturer, manufacturer_id)
    if manufacturer is None or manufacturer.current_version is None:
        return None
    return ManufacturerRef(id=manufacturer.id, name=manufacturer.current_version.name)


def _product_warnings(session: Session, product_id: str, version_number: int) -> list[WarningRef]:
    warnings = session.execute(
        sa.select(Warning).where(
            Warning.product_id == product_id,
            Warning.version_number == version_number,
            Warning.status == RecordStatus.ACTIVE,
        )
    ).scalars()
    return [WarningRef(category=w.category.value, text=w.text) for w in warnings]


def _product_recalls(session: Session, product_id: str) -> list[RecallRef]:
    recalls = session.execute(sa.select(Recall).where(Recall.product_id == product_id)).scalars()
    return [
        RecallRef(
            id=r.id, reason=r.reason, classification=r.classification.value, status=r.status.value
        )
        for r in recalls
    ]


def search_products(
    session: Session,
    query: str,
    *,
    limit: int = 20,
    tsquery_builder: TsqueryBuilder = build_tsquery,
) -> list[ProductHit]:
    tsquery = tsquery_builder(query)
    rows = session.execute(
        sa.select(Product.id, sa.func.ts_rank(ProductVersion.search_vector, tsquery).label("rank"))
        .join(ProductVersion, ProductVersion.id == Product.current_version_id)
        .where(
            ProductVersion.search_vector.op("@@")(tsquery),
            ProductVersion.status == RecordStatus.ACTIVE,
        )
        .order_by(sa.desc("rank"))
        .limit(limit)
    ).all()

    hits = []
    for product_id, rank in rows:
        product = session.get(Product, product_id)
        assert product is not None and product.current_version is not None
        current = product.current_version
        hits.append(
            ProductHit(
                id=product.id,
                name=current.name,
                product_type=current.product_type,
                dosage_form=current.dosage_form,
                manufacturer=_product_manufacturer(session, current.manufacturer_id),
                ingredients=_product_ingredients(session, current.id),
                warnings=_product_warnings(session, product.id, current.version_number),
                recalls=_product_recalls(session, product.id),
                rank=float(rank),
                source=_provenance(session, current.source_id),
                external_url=_dailymed_label_url(session, product.id),
            )
        )
    return hits


@dataclass(frozen=True)
class ProductRef:
    id: str
    name: str


@dataclass(frozen=True)
class WarningHit:
    id: int
    category: str
    text: str
    rank: float
    product: ProductRef
    source: Provenance
    external_url: str | None


def search_warnings(
    session: Session,
    query: str,
    *,
    limit: int = 20,
    tsquery_builder: TsqueryBuilder = build_tsquery,
) -> list[WarningHit]:
    tsquery = tsquery_builder(query)
    rows = session.execute(
        sa.select(Warning, sa.func.ts_rank(Warning.search_vector, tsquery).label("rank"))
        .where(Warning.search_vector.op("@@")(tsquery), Warning.status == RecordStatus.ACTIVE)
        .order_by(sa.desc("rank"))
        .limit(limit)
    ).all()

    hits = []
    for warning, rank in rows:
        product = session.get(Product, warning.product_id)
        product_name = (
            product.current_version.name
            if product is not None and product.current_version is not None
            else "?"
        )
        hits.append(
            WarningHit(
                id=warning.id,
                category=warning.category.value,
                text=warning.text,
                rank=float(rank),
                product=ProductRef(id=warning.product_id, name=product_name),
                source=_provenance(session, warning.source_id),
                external_url=_dailymed_label_url(session, warning.product_id),
            )
        )
    return hits


@dataclass(frozen=True)
class RecallHit:
    id: int
    reason: str
    classification: str
    status: str
    rank: float
    product: ProductRef | None
    manufacturer: ManufacturerRef | None
    source: Provenance
    external_url: str | None


def search_recalls(
    session: Session,
    query: str,
    *,
    limit: int = 20,
    tsquery_builder: TsqueryBuilder = build_tsquery,
) -> list[RecallHit]:
    tsquery = tsquery_builder(query)
    rows = session.execute(
        sa.select(Recall, sa.func.ts_rank(Recall.search_vector, tsquery).label("rank"))
        .where(Recall.search_vector.op("@@")(tsquery))
        .order_by(sa.desc("rank"))
        .limit(limit)
    ).all()

    hits = []
    for recall, rank in rows:
        product_ref = None
        external_url = None
        if recall.product_id is not None:
            product = session.get(Product, recall.product_id)
            if product is not None and product.current_version is not None:
                product_ref = ProductRef(id=product.id, name=product.current_version.name)
                external_url = _dailymed_label_url(session, recall.product_id)
        hits.append(
            RecallHit(
                id=recall.id,
                reason=recall.reason,
                classification=recall.classification.value,
                status=recall.status.value,
                rank=float(rank),
                product=product_ref,
                manufacturer=_product_manufacturer(session, recall.manufacturer_id),
                source=_provenance(session, recall.source_id),
                external_url=external_url,
            )
        )
    return hits
