"""core schema

Revision ID: 4a13a0735787
Revises: 
Create Date: 2026-07-29 14:10:53.681734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a13a0735787'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_resolution_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('ingredient', 'manufacturer', 'product', name='entitytype', native_enum=False), nullable=False),
    sa.Column('candidate_a_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_b_id', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='ingestionrunstatus', native_enum=False), nullable=False),
    sa.Column('checkpoint_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_validated', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_logs_source_status_started', 'ingestion_logs', ['source', 'status', 'started_at'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('endpoint_or_document_type', sa.String(length=128), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=64), nullable=False),
    sa.Column('raw_payload_ref', sa.String(length=512), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('ingredient', 'manufacturer', 'product', name='entitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('alias_text', sa.String(length=256), nullable=False),
    sa.Column('normalized_alias_text', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aliases_entity', 'aliases', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_aliases_normalized_alias_text', 'aliases', ['normalized_alias_text'], unique=False)
    op.create_table('ingredient_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('active', 'retracted', 'superseded', 'withdrawn', name='recordstatus', native_enum=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'version_number', name='uq_ingredient_versions_entity_version')
    )
    op.create_index('ix_ingredient_versions_entity_version', 'ingredient_versions', ['ingredient_id', 'version_number'], unique=False)
    op.create_index('ix_ingredient_versions_normalized_name', 'ingredient_versions', ['normalized_name'], unique=False)
    op.create_table('manufacturer_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('active', 'retracted', 'superseded', 'withdrawn', name='recordstatus', native_enum=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id', 'version_number', name='uq_manufacturer_versions_entity_version')
    )
    op.create_index('ix_manufacturer_versions_entity_version', 'manufacturer_versions', ['manufacturer_id', 'version_number'], unique=False)
    op.create_index('ix_manufacturer_versions_normalized_name', 'manufacturer_versions', ['normalized_name'], unique=False)
    op.create_table('product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('product_type', sa.String(length=128), nullable=True),
    sa.Column('dosage_form', sa.String(length=128), nullable=True),
    sa.Column('manufacturer_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('active', 'retracted', 'superseded', 'withdrawn', name='recordstatus', native_enum=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version_number', name='uq_product_versions_entity_version')
    )
    op.create_index('ix_product_versions_entity_version', 'product_versions', ['product_id', 'version_number'], unique=False)
    op.create_table('recalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('manufacturer_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('class_i', 'class_ii', 'class_iii', 'unclassified', name='recallclassification', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ongoing', 'completed', 'terminated', name='recallstatus', native_enum=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('ingredient', 'manufacturer', 'product', name='entitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.Enum('cas', 'unii', 'ndc', 'spl_set_id', 'openfda_id', 'fda_labeler_code', name='referencetype', native_enum=False), nullable=False),
    sa.Column('reference_value', sa.String(length=256), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_references_entity', 'references', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_references_type_value', 'references', ['reference_type', 'reference_value'], unique=False)
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('boxed_warning', 'contraindication', 'precaution', name='warningcategory', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'retracted', 'superseded', 'withdrawn', name='recordstatus', native_enum=False), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warnings_product_version', 'warnings', ['product_id', 'version_number'], unique=False)
    op.create_table('product_ingredients',
    sa.Column('product_version_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('active', 'inactive', name='productingredientrole', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_version_id', 'ingredient_id')
    )
    # ### end Alembic commands ###

    # `current_version_id` FKs are circular (identity <-> version tables) and must be
    # added after both sides of each pair exist — see DATABASE_DESIGN.md Section 2.
    op.create_foreign_key(
        'fk_ingredients_current_version_id',
        'ingredients', 'ingredient_versions', ['current_version_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_manufacturers_current_version_id',
        'manufacturers', 'manufacturer_versions', ['current_version_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_products_current_version_id',
        'products', 'product_versions', ['current_version_id'], ['id'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_products_current_version_id', 'products', type_='foreignkey')
    op.drop_constraint('fk_manufacturers_current_version_id', 'manufacturers', type_='foreignkey')
    op.drop_constraint('fk_ingredients_current_version_id', 'ingredients', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_ingredients')
    op.drop_index('ix_warnings_product_version', table_name='warnings')
    op.drop_table('warnings')
    op.drop_index('ix_references_type_value', table_name='references')
    op.drop_index('ix_references_entity', table_name='references')
    op.drop_table('references')
    op.drop_table('recalls')
    op.drop_index('ix_product_versions_entity_version', table_name='product_versions')
    op.drop_table('product_versions')
    op.drop_index('ix_manufacturer_versions_normalized_name', table_name='manufacturer_versions')
    op.drop_index('ix_manufacturer_versions_entity_version', table_name='manufacturer_versions')
    op.drop_table('manufacturer_versions')
    op.drop_index('ix_ingredient_versions_normalized_name', table_name='ingredient_versions')
    op.drop_index('ix_ingredient_versions_entity_version', table_name='ingredient_versions')
    op.drop_table('ingredient_versions')
    op.drop_index('ix_aliases_normalized_alias_text', table_name='aliases')
    op.drop_index('ix_aliases_entity', table_name='aliases')
    op.drop_table('aliases')
    op.drop_table('sources')
    op.drop_table('products')
    op.drop_table('manufacturers')
    op.drop_table('ingredients')
    op.drop_index('ix_ingestion_logs_source_status_started', table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_table('entity_resolution_reviews')
    # ### end Alembic commands ###
